services:
  chroma:
    image: ghcr.io/chroma-core/chroma:latest
    container_name: chroma_server 
    ports:
      - "${CHROMA_PORT}:8000" 
    volumes:
      - ./data/chroma:/chroma/data 
    environment: 
      - CHROMA_SERVER_HOST=0.0.0.0 
      - CHROMA_SERVER_HTTP_PORT=8000 
      - CHROMA_HOME=/chroma/data 
    healthcheck: 
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/heartbeat"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s 
    restart: unless-stopped 

  streamlit_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: streamlit_app
    ports:
      - "${STREAMLIT_PORT}:8501"
    env_file:
      - .env
    environment:
      - STREAMLIT_SERVER_HEADLESS=true
    depends_on:
      - chroma
    restart: unless-stopped
